# Generated by Django 5.1.1 on 2024-09-15 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название для категории')),
            ],
            options={
                'verbose_name': 'Категории автора',
                'verbose_name_plural': 'Категории авторов',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=1, unique=True, verbose_name='Буква')),
            ],
            options={
                'verbose_name': 'Буква',
                'verbose_name_plural': 'Буквы',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и Фамилия автора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='hamster_hole.authorcategory', verbose_name='Категория автора')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='hamster_hole.letter', verbose_name='Буква для автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructions/images/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='instructions/files/', verbose_name='Файл')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='hamster_hole.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Инструкция',
                'verbose_name_plural': 'Инструкции',
            },
        ),
    ]
